### ISSUE TITLE
What is the scope of this project?

### ISSUE THREAD

**Issue by joekarl** [codeforokc/school-finder#16]
Just looking to get a better handle on what we're actually building.

From the sounds of it, we'll want to support looking up:
* school district for a location
* closest schools to a location
* schools that one would send one's kids to based on location (not necessarily the closest schools)

Currently, we don't have that data from the city to do the lookups for the third thing, we'll need to get that data from individual school districts. (ie inner district boundaries) 

Reason I ask is we need to know what relationships need to be built between datasets (also this would be good info to have as part of the README in terms of defining the scope of this project).

//cc @codeforokc/school-finder-team @codeforokc/owners

**Comment by joekarl** [comment]
(I realize now there's some technical discussion over here https://github.com/codeforokc/discussions/issues/1#issue-49974092 but still missing what features we are looking to implement as part of a finished product)

**Comment by jagthedrummer** [comment]
For the first stage I think just covering 1 & 2 would be good enough. The third feature would be nice, but as you say will require data that we don't have as of yet. I think we can make progress on the first two and save the third as an update once we have something actually working. Just my $0.02, what does everyone else think?

**Comment by joekarl** [comment]
I wonder if a school finder without feature 3 is even a useful product... 
As a user, I'm not sure what locating the closest school does for me.
I think that would lead to confusion and questions from users who think that the app isn't working properly because it doesn't do what the user expects it to.

I suppose it depends on who we're targeting.
Are we targeting people who want to lookup which school district they're in and what school's their kids will be going to? If so, I would think feature 3 is a feature we need to have from day one.
If we're not targeting those users, who are our users and how do we see them using the app?

We should be able to get said school district data fairly easily... (see https://github.com/codeforokc/school-finder/issues/5#issuecomment-68644867)

**Comment by joekarl** [comment]
Heh, that wasn't meant to sound confrontational, just asking questions that I don't see written down answers to anywhere.

**Comment by jagthedrummer** [comment]
No worries, I was just off line most of last evening. Those are all fair points.

Re: "Who are our users and how do we see them using the app?" - I'm not sure that I (we?) have any good answers to that question as of yet.

As @mkchandler pointed out here (https://github.com/codeforokc/discussions/issues/1#issuecomment-65915221) there is already a site that does a good deal (if not all) of what we're talking about doing. I had advocated that we should still build at least a simple version of this app as a kind of "training wheels" project that lets us figure out how we're going to coordinate working together, how to deal with geo data, etc... I'm open to the possibility that this is not a good way to think about it. But, *if* that's how we're approaching the project, then I'd hate to see work on features 1 & 2 get held up because we don't yet know how we're going to do #3. (When I mentioned "stage 1" above, I didn't really mean "ship it to the public stage 1".)

Thoughts?

**Comment by joekarl** [comment]
Okay, sounds good. Will add some of this information to the main README.

**Comment by jagthedrummer** [comment]
Thanks for leading the charge on this project, @joekarl! :clap:

**Comment by joekarl** [comment]
Just added a simple checklist to the README (#17)

**Comment by mkchandler** [comment]
I've been offline for the past 4 days, so just now catching up on all this :-)

I agree with @jagthedrummer, let's keep moving forward with the first two items. I will get in touch with some of my contacts in the city/school system to see if we can get inner district boundaries.

And as Jeremy said, thanks for all your hard work on this @joekarl!

**Comment by mkchandler** [comment]
We have nailed down the scope, but the specific features can be viewed in #66
