### ISSUE TITLE
Gulp Build System

### ISSUE THREAD

**Issue by vantreeseba** [codeforokc/school-finder#18]

**Comment by joekarl** [comment]
A nice to have would be conditional resources based on dev vs build.
Something like https://www.npmjs.com/package/gulp-useref or https://www.npmjs.com/package/gulp-html-replace.
You probably already have something lined up for this but would make it so that one could in theory just clone the repo and open the index.html file and be running the app (ie no `gulp server` or anything).

**Comment by vantreeseba** [comment]
I'll check those out.

**Comment by mkchandler** [comment]
Closing this as we are not worried about gulp right now.
