### ISSUE TITLE
implement twitter bootstrap

### ISSUE THREAD

**Issue by vantreeseba** [codeforokc/school-finder#31]

**Comment by mbockus** [comment]
I'm making an attempt to resolve this issue using the gulp-angular generator.

**Comment by mkchandler** [comment]
Was this for bootstrapping the angular setup, or for twitter bootstrap?

**Comment by DevinClark** [comment]
Sounds like Twitter bootstrap. I believe there was another issue for angular setup.

**Comment by mkchandler** [comment]
@DevinClark Ok, that's what I thought.
@mbockus I think the angular setup was #30, which has already been closed.

**Comment by mbockus** [comment]
Oh, whoops. I thought it was referring to bootstrapping the project. I think I combined #30 and #18 potentially. I thought we talked about using yeoman at the meeting and that was the way we were going to go. Is that no longer the case? I thought I was just stealing an action item from @vantreeseba.

**Comment by DevinClark** [comment]
@mbockus, @joekarl and a few others discussed it in the techlahoma irc channel and decided against yeoman.

**Comment by joekarl** [comment]
Sorry this was confusing, this should be for pulling in twitter bootstrap. I think we've got the angular app bootstrapped and up and running.

**Comment by joekarl** [comment]
@mbockus yeah I wanted to get the angular bootstrapping out of the way so went ahead and implemented it over in #32, again sorry for the confusion.

**Comment by mbockus** [comment]
@joekarl @DevinClark I gotcha. I didn't know that decision had been made, so I was just taking a stab at it. What were the reasons to not go with yeoman? I like the bower injection, live reload, project structure, etc. Adding all that stuff manually seems like a pain. I'm not a pro IRC user. Is there a way to get this history of the #codeforokc channel?

**Comment by joekarl** [comment]
I don't know that we have any of the #techlahoma logs unfortunately.
But to sum it up, I initially went with yeoman but there were just too many decisions being made without fully understanding what/why they were being made (things like build pipeline, dev tools, etc). So after some discussion and digging around the documentation, it turns out that angular is really really simple to pull together so just did the initial setup manually.

While I agree it's a pain to have to add in pieces manually, it's a pain to have to strip out pieces that we don't need (especially when we don't know what we don't need at this point). Easier to only add what we need as we go than have a pile of tools that we don't use. 

The main focus was just to get some sort of base for people to contribute to and I think we're solidly there.

**Comment by Mike-Loffland** [comment]
Is the Techlahoma IRC channel the primary means of communication?

**Comment by DevinClark** [comment]
@Mike-Loffland #techlahoma is a good place to be, regardless. We also have the codeforokc gitter channel, which we should probably be using for those kinds of conversations.

**Comment by Mike-Loffland** [comment]
Thanks... I'll tune into both.

**Comment by DevinClark** [comment]
@joekarl I was able to go back a little bit (just from my bouncer). https://gist.github.com/DevinClark/5f67bcd91cbd3f7cfd3f

**Comment by mbockus** [comment]
@joekarl @DevinClark Thank for the info. I'll stay in the irc channels as well so I can stay in the loop.
